import { expertise, timeline, cases, profile, tools, education } from '@/data/profile';

export function Positioning(){return <section className="section"><div className="glass rounded-[42px] p-8 md:p-12"><p className="kicker">Positioning</p><div className="mt-5 grid gap-8 lg:grid-cols-[.9fr_1.1fr]"><h2 className="text-4xl font-black tracking-[-.04em] md:text-6xl">Where academic excellence meets AI evaluation.</h2><div className="space-y-5 text-lg leading-8 text-slate-300"><p>Fatih is positioned at the intersection of language, education and artificial intelligence. His academic background supports the careful judgment required in AI evaluation: diagnosing errors, explaining reasoning, applying rubrics, and giving structured feedback.</p><p>This makes his profile especially relevant for LLM evaluation, red teaming, localization, multilingual QA, and human-in-the-loop AI workflows.</p></div></div></div></section>}

export function Expertise(){return <section id="expertise" className="section"><p className="kicker">Core Expertise</p><h2 className="mt-4 max-w-4xl text-5xl font-black tracking-[-.04em] md:text-6xl">Language expertise built for modern AI systems.</h2><div className="mt-10 grid gap-5 md:grid-cols-2">{expertise.map((e)=><div className="glass card-hover rounded-[34px] p-7" key={e.title}><div className="text-sm font-black text-cyan">{e.eyebrow}</div><h3 className="mt-3 text-2xl font-black">{e.title}</h3><p className="mt-3 leading-7 text-slate-300">{e.text}</p><ul className="mt-5 grid gap-3 text-slate-300">{e.items.map(item=><li key={item} className="flex gap-3"><span className="mt-2 h-2 w-2 shrink-0 rounded-full bg-cyan" />{item}</li>)}</ul></div>)}</div></section>}

export function Experience(){return <section id="experience" className="section"><p className="kicker">Experience</p><h2 className="mt-4 max-w-4xl text-5xl font-black tracking-[-.04em] md:text-6xl">A career built around language, systems and quality.</h2><div className="relative mt-12"><div className="timeline-line absolute bottom-0 left-3 top-0 hidden w-px md:block" />{timeline.map(t=><div key={t.role} className="relative mb-6 md:pl-12"><div className="absolute left-0 top-7 hidden h-6 w-6 rounded-full border border-cyan/50 bg-cyan/20 md:block" /><div className="glass card-hover rounded-[30px] p-6 md:grid md:grid-cols-[220px_1fr] md:gap-8"><div className="font-black text-cyan">{t.period}</div><div><h3 className="text-2xl font-black">{t.role}</h3><p className="mt-1 font-bold text-slate-300">{t.org}</p><p className="mt-3 leading-7 text-slate-300">{t.text}</p></div></div></div>)}</div></section>}

export function AICases(){return <section id="ai-cases" className="section"><p className="kicker">AI Case Studies</p><h2 className="mt-4 max-w-4xl text-5xl font-black tracking-[-.04em] md:text-6xl">NDA-safe examples of the problems I help solve.</h2><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{cases.map(c=><div key={c.title} className="card-hover rounded-[32px] border border-white/10 bg-white/[.04] p-7"><div className="mb-4 inline-flex rounded-full border border-cyan/20 bg-cyan/10 px-3 py-1 text-xs font-black text-cyan">{c.type}</div><h3 className="text-2xl font-black">{c.title}</h3><p className="mt-4 leading-7 text-slate-300">{c.text}</p></div>)}</div></section>}

export function Skills(){return <section className="section"><p className="kicker">Tools & Skills</p><h2 className="mt-4 max-w-4xl text-5xl font-black tracking-[-.04em] md:text-6xl">Practical skills across AI, language and assessment.</h2><div className="mt-10 flex flex-wrap gap-3">{tools.map(t=><span key={t} className="rounded-full border border-white/12 bg-white/[.055] px-5 py-3 text-sm font-bold text-slate-200">{t}</span>)}</div></section>}

export function Education(){return <section id="education" className="section"><p className="kicker">Education</p><h2 className="mt-4 text-5xl font-black tracking-[-.04em] md:text-6xl">Academic foundation.</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{education.map(e=><div key={e.degree} className="glass card-hover rounded-[30px] p-6"><div className="text-sm font-black text-cyan">{e.year}</div><h3 className="mt-3 text-xl font-black">{e.degree}</h3><p className="mt-3 leading-7 text-slate-300">{e.school}</p></div>)}</div></section>}

export function Contact(){return <section id="contact" className="section"><div className="glass rounded-[42px] p-9 md:p-14"><p className="kicker">Contact</p><h2 className="mt-4 max-w-3xl text-5xl font-black tracking-[-.04em] md:text-6xl">Let’s build better AI through language.</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-300">Available for AI evaluation, red teaming, localization, translation, linguistic QA and language technology projects.</p><div className="mt-8 flex flex-wrap gap-4"><a className="btn-primary" href={`mailto:${profile.email}`}>Email Me</a><a className="btn-ghost" href={profile.linkedin}>LinkedIn</a><a className="btn-ghost" href={profile.upwork}>Upwork</a><a className="btn-ghost" href="/cv/fatih-ercan-cv.pdf">Download CV</a></div></div></section>}
